import type { NextPage } from "next";
import Head from "next/head";
import { Me } from "../components/me";

const Home: NextPage = () => {
  return (
    <div className="p-3 space-y-3">
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Me />
      <div className="bg-black/10 dark:bg-white/10 w-full p-3">
        <p>## Title</p>
        <p># Heading 2</p>
      </div>
    </div>
  );
};

export default Home;
